-- 코드를 입력하세요

SELECT
    AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM(

SELECT
    B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, (SALES * PRICE) AS TOTAL_SALES
FROM
    (
        SELECT
            BOOK_ID, SUM(SALES) AS SALES
        FROM BOOK_SALES
        WHERE TO_CHAR(SALES_DATE, 'YYYY-MM-DD') LIKE '2022-01%'
        GROUP BY BOOK_ID) A,
    BOOK B,
    AUTHOR C
WHERE A.BOOK_ID = B.BOOK_ID
    AND B.AUTHOR_ID = C.AUTHOR_ID
)
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC