-- 코드를 입력하세요
SELECT A.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM
    REST_INFO A,
    (
    SELECT FOOD_TYPE, MAX 
    FROM(
        SELECT
            FOOD_TYPE, MAX(FAVORITES) AS MAX
        FROM REST_INFO
        GROUP BY FOOD_TYPE
        )
        ) B
WHERE A.FOOD_TYPE = B.FOOD_TYPE
    AND A.FAVORITES = B.MAX
ORDER BY FOOD_TYPE DESC