-- 코드를 입력하세요
SELECT
    MEMBER_NAME, REVIEW_TEXT, TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM
    MEMBER_PROFILE A,
    (SELECT
        A.MEMBER_ID, REVIEW_TEXT, REVIEW_DATE
    FROM
        (SELECT
            MEMBER_ID
        FROM
            (SELECT
                MEMBER_ID, COUNT(MEMBER_ID) AS COUNT
            FROM
                REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY COUNT DESC)
        WHERE ROWNUM = 1) A,
        REST_REVIEW B
    WHERE A.MEMBER_ID = B.MEMBER_ID) B
WHERE
    A.MEMBER_ID = B.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT