-- 코드를 입력하세요
SELECT
    CATEGORY,
    SUM(SALES) AS TOTAL_SALES
FROM
    (SELECT
        BOOK_ID,
        SUM(SALES) AS SALES
    FROM
        BOOK_SALES
    WHERE
        TO_CHAR(SALES_DATE, 'YYYY-MM-DD') LIKE '2022-01%'
    GROUP BY BOOK_ID) A,
    BOOK B
WHERE A.BOOK_ID = B.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY