-- 코드를 입력하세요
SELECT
    A.CATEGORY,
    MAX_PRICE,
    PRODUCT_NAME
FROM
    (
    SELECT
        CATEGORY,
        MAX(PRICE) AS MAX_PRICE
    FROM
        FOOD_PRODUCT
    WHERE
        CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
    ORDER BY MAX(PRICE)) A,
    FOOD_PRODUCT B
WHERE
    MAX_PRICE = PRICE
    AND A.CATEGORY = B.CATEGORY
ORDER BY MAX_PRICE DESC;

